feat: create certificate screen
dojot/gui-v2 pull request #115
Opened 2021-12-22 13:57 UTC by LeonamMoura

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

dojot/dojot#2298

2021-12-22 16:15 UTC, LuanEdCosta requested changes

2021-12-22 16:15 UTC, LuanEdCosta commented on src/js/views/createCertificate/View.jsx
> +          <Button onClick={() => setExpanded('')} className={classes.cancelButton}>
I think that the cancel button should go back to the previous page (if there is one) or go to `/certificates`

Example:
```javascript
const history = useHistory();

const handleLeaveTemplateCreation = () => {
  if (history.length) history.goBack();
  else history.push('/templates');
};
```

2021-12-22 16:15 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/en.createCertificate.i18n.json
> +    "generateCsrHelp": "How to generate a CSR ?",
Remove the space before `?`

2021-12-22 16:15 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/en.createCertificate.i18n.json
> +      "step1_text": "Run the command openssl req  -newkey 'rsa:2048'  -nodes  -sha256  -keyout 'privatekey.pem'  -out 'csr.pem'  -subj '/CN=Any value'",
1. Use calmelCase, not snake_case, because i18next use _ to its features like `_plural`
2. I think there is two spaces between the command arguments

2021-12-23 13:29 UTC, LuanEdCosta approved these changes
🚀

2021-12-27 14:17 UTC, cfrancisco commented on src/js/views/createCertificate/View.jsx
> +          {expanded !== CONSTANTS.CA && (
Sounds a bit confusing to me checking '!==', I know that is for making less code but is also less comprehensive.

2021-12-27 14:27 UTC, cfrancisco approved these changes

2021-12-27 14:27 UTC, cfrancisco commented on src/js/views/createCertificate/layout/CollapsibleCard.jsx
> +      {creationMethod === CONSTANTS.ONE_CLICK_CREATE && <CreateCertificateOneClick />}
That's is better! kk

2021-12-27 14:27 UTC, cfrancisco commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +    "subTitle": "Mais prático: A plataforma gera o certificado e a chave privada para o dispositivo"
Great and useful tips for the users, nice job!

2021-12-27 14:27 UTC, cfrancisco commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +    "subTitle": "Mais seguro: A plataforma gera um certificado, mas não tem conhecimento da chave privada.",
mas sem ter conhecimento da sua chave privada* Maybe sounds more informative (the same in English)

2021-12-27 14:27 UTC, cfrancisco commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +      "step2Text": "Copie e conteúdo do arquivo csr.pem para a area de texto abaixo"
E cole para a caixa de texto abaixo*

2021-12-27 14:27 UTC, cfrancisco commented on src/js/views/createCertificate/translations/en.createCertificate.i18n.json
> +    "subTitle": "Enables you to use your existing public key infrastructure",
Allows you*

2021-12-27 16:51 UTC, merged