adjust placeholders of certificate and ca creation to get more intuit…
dojot/gui-v2 pull request #145
Opened 2022-01-27 21:48 UTC by LeonamMoura

…ive for the user

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
refactor

* **What is the current behavior?** (You can also link to an open issue here)
CA creation and Certificate Creation (CA, CSR) placeholder texts were not user-intuitive

* **What is the new behavior (if this is a feature change)?**
The texts has been changed for improve the user experience

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2452

* **Other information**:

2022-01-28 13:33 UTC, LuanEdCosta requested changes
**Idea:** Maybe you can add a label for TextFields, because when the user type something the placeholder disappears. 

What do you think?

2022-01-28 13:33 UTC, LuanEdCosta commented on config/development.json
> +  "publicPath": "/v2"
I don't know if this will cause any problems, but you can leave the pulicPath as it was before.

2022-01-28 13:33 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +    "inputPlaceholder": "Copie e cole o conteúdo do arquivo .pem aqui."
I think that this text should be `Cole o conteúdo do arquivo .pem aqui.`, because the label already tells the user to copy.

2022-01-28 13:33 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +    "inputPlaceholder": "Copie e cole o conteúdo do arquivo .pem aqui.",
I think that this text should be `Cole o conteúdo do arquivo .pem aqui.`, because the label already tells the user to copy.

2022-01-28 13:33 UTC, LuanEdCosta commented on src/js/views/createCertificationAuthority/translations/en.createCertificationAuthority.json
> +  "caPemLabel": "Copy and paste the content of the .pem file here"
I think that this text should be `Paste the content of the .pem file here.`.

2022-01-28 13:33 UTC, LuanEdCosta commented on src/js/views/createCertificationAuthority/translations/pt_br.createCertificationAuthority.json
> +  "caPemLabel": "Copie e cole o conteúdo do arquivo .pem aqui"
I think that this text should be `Paste the content of the .pem file here.`.

2022-01-31 14:17 UTC, LuanEdCosta approved these changes
:+1:

2022-01-31 16:23 UTC, luisfelipefurlan approved these changes

2022-01-31 16:41 UTC, merged