Issue#2483: enable copy help texts csr method of certificate creation
dojot/gui-v2 pull request #153
Opened 2022-02-10 16:46 UTC by LeonamMoura

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2483

* **Other information**:

2022-02-11 14:37 UTC, LuanEdCosta reviewed
@LeonamMoura Maybe you can add the copy to clipboard button that you created some days ago to allow the user to copy the command. What do you think?

2022-02-14 14:47 UTC, LuanEdCosta requested changes

2022-02-14 14:47 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/en.createCertificate.i18n.json
> +      "generateCsrCommand": "openssl req  -newkey 'rsa:2048'  -nodes  -sha256  -keyout 'privatekey.pem'  -out 'csr.pem'  -subj '/CN=Any value'",
You can remove the extra white space between command options

2022-02-14 14:47 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +      "generateCsrCommand": "openssl req  -newkey 'rsa:2048'  -nodes  -sha256  -keyout 'privatekey.pem'  -out 'csr.pem'  -subj '/CN=Any value'",
You can remove the extra white space between command options

2022-02-14 14:47 UTC, LuanEdCosta commented on src/js/views/createCertificate/layout/style.js
> +    marginLeft: theme.spacing(1),
I think that a `marginRight` would be great and maybe you can set a fixed width for the input.

2022-02-14 14:47 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/en.createCertificate.i18n.json
>        "step1": "Step 1: ",
The text has a white space, but for some reason it is not shown on screen.

![image](https://user-images.githubusercontent.com/36794274/153885342-f7735613-4ea4-46c3-93a3-b2eb3a0e70ba.png)

2022-02-14 14:47 UTC, LuanEdCosta commented on src/js/views/createCertificate/translations/pt_br.createCertificate.i18n.json
> +      "runTheCommand": "Execute o comando",
Missing `:`

The english translation has `:`
![image](https://user-images.githubusercontent.com/36794274/153885798-e19385fd-b6bb-4a04-adaf-3905ec2cb17c.png)

2022-02-16 15:51 UTC, LuanEdCosta approved these changes

2022-02-16 16:52 UTC, luisfelipefurlan approved these changes

2022-02-17 12:07 UTC, merged