NX Feat: Favorite Devices
dojot/gui-v2 pull request #167
Opened 2022-03-29 16:12 UTC by LeonamMoura

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feat

* **What is the current behavior?** (You can also link to an open issue here)
dojot/dojot#2412

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-04-11 16:45 UTC, LuanEdCosta requested changes

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/redux/sagas/devicesSaga.js
> +    // yield put(successActions.showSuccessToast({ i18nMessage: 'favoriteDevice' }));
I believe that we should show a success message to the user. What do you think?

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/devices/layout/DataTable.jsx
> +  console.log(devices);
You can remove this line

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/devices/layout/DataTable.jsx
> +            startExtraCells={<TableCell />} // TODO: Show again when you can favorite devices
Remove the TODO comment

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/devices/layout/DataTable.jsx
> +                          // disabled
Remove commented code

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/devices/layout/MassActions.jsx
>          {false && (
This component will never render :laughing:

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/home/View.jsx
> +          size: 10,
What if I have more than 10 favorite devices? 
What if I have 2 favorite devices but they are in page 4?
:thinking:

2022-04-11 16:45 UTC, LuanEdCosta commented on src/js/views/home/View.jsx
> +    console.log('devices => ', devices);
You can remove this line

2022-06-08 18:02 UTC, LuanEdCosta requested changes

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/common/i18n/translations/en.success.i18n.json
> -    "createCertificate": "Certificate created",
Why this line is being removed?

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/common/i18n/translations/pt_br.success.i18n.json
> -    "createCertificate": "Certificado criado",
Why this line is being removed?

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/redux/sagas/devicesSaga.js
> +    yield put(loadingActions.removeLoading(constants.GET_DEVICE_BY_ID));
You should remove the loading using `constants.GET_FAVORITE_DEVICES`

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/redux/sagas/devicesSaga.js
> +    if (!favoriteDevices)
I recommend you to use the `else` statement or a ternary operator `true ? x : y` instead of two IFs.

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/redux/selectors/devicesSelector.js
> +export const favoriteDeviceSelector = createSelector(
You need to create a test case for this selector. Check out the `__tests__` folder located in the same level of this file.

2022-06-08 18:02 UTC, LuanEdCosta commented on src/js/views/devices/layout/DataTable.jsx
> +                          // disabled
Remove this comment

2022-06-09 13:10 UTC, LeonamMoura commented on src/js/common/i18n/translations/en.success.i18n.json
> -    "createCertificate": "Certificate created",
Because in the nx/development branch this translation is duplicated in the en.success.i18n.json file

2022-06-09 13:10 UTC, LeonamMoura commented on src/js/common/i18n/translations/pt_br.success.i18n.json
> -    "createCertificate": "Certificado criado",
Because in the nx/development branch this translation is duplicated in the pt_br.success.i18n.json file

2022-06-09 13:23 UTC, LuanEdCosta commented on src/js/common/i18n/translations/pt_br.success.i18n.json
> -    "createCertificate": "Certificado criado",
Oh sorry, I just noticed it now.

2022-06-09 20:45 UTC, LuanEdCosta commented
It worked very well. I just want to say that we can (in a future PR) add something in device cards to indicate that is, in fact, a device card and not a link to a page as the other cards.

![image](https://user-images.githubusercontent.com/36794274/172941222-b5d746e7-9409-4269-885a-69feab43c050.png)

2022-06-09 20:47 UTC, LuanEdCosta approved these changes

2022-06-15 16:17 UTC, luisfelipefurlan approved these changes

2022-06-15 16:51 UTC, merged