NX Feat: Set a ID for devices - Issue#2543
dojot/gui-v2 pull request #168
Opened 2022-04-20 11:40 UTC by LeonamMoura

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
before it was not possible to set an id for the device by GUI-NX

* **What is the new behavior (if this is a feature change)?**
It is now possible to set an ID of 2 to 6 mandatory hexadecimal characters

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2543

* **Other information**:

2022-05-11 16:16 UTC, LuanEdCosta requested changes
Some small details...

2022-05-11 16:16 UTC, LuanEdCosta commented on src/js/views/createDevice/steps/SummaryStep/SummaryStep.jsx
>  SummaryStep.propTypes = {
Missing `setDeviceId` prop type definition

2022-05-11 16:16 UTC, LuanEdCosta commented on src/js/views/createDevice/translations/pt_br.createDevice.i18n.json
> +    "deviceIdHint": "Opcional. Caso não seja preenchido, o Id do dispositivo será gerado automaticamente pela dojot.",
You can remove the last part "pela dojot"

2022-05-13 17:07 UTC, luisfelipefurlan requested changes

2022-05-13 17:07 UTC, luisfelipefurlan commented on src/js/views/createDevice/View.jsx
> +  const [deviceId, setDeviceId] = useState('');
you can initialize the variable with null instead of ''

2022-05-13 17:07 UTC, luisfelipefurlan commented on src/js/views/createDevice/View.jsx
> +        id: deviceId.trim() === '' ? null : deviceId,
if you initialize the variable with null, this validation will not be necessary

2022-05-13 17:07 UTC, luisfelipefurlan commented on src/js/views/createDevice/steps/SummaryStep/SummaryStep.jsx
> +    setDeviceId('');
you can set it to null

2022-05-16 16:41 UTC, LuanEdCosta approved these changes, later dismissed
I agree with Luis, but I didn't find anything else to fix, so I'm approving.

2022-05-26 12:00 UTC, LuanEdCosta approved these changes

2022-05-26 13:02 UTC, luisfelipefurlan approved these changes

2022-05-26 13:30 UTC, merged