2598 - Adjust toast message for 'Use My Certificate'
dojot/gui-v2 pull request #183
Opened 2022-06-30 15:43 UTC by LeonamMoura

Corrected success toast:
![image](https://user-images.githubusercontent.com/63542473/176719591-a9e39ab6-6bad-4d06-821d-0b4d3135f3bf.png)

Corrected error toast:
![image](https://user-images.githubusercontent.com/63542473/176719774-4b489c78-d19f-4371-ae7f-18a4f1c96f3a.png)

dojot/dojot#2598

2022-07-05 15:52 UTC, LuanEdCosta requested changes
You forgot to edit the success and error translation files of the other micro applications. Even though some of them will never be used, you should edit them to maintain the consistency.

2022-07-05 15:52 UTC, LuanEdCosta commented on MFE/container/src/i18n/translations/pt_br.error.i18n.json
> +    "addedCertificate": "Não foi possível adicionar o Certificado",
"Certificado" should be lowercase.

2022-07-06 14:31 UTC, LeonamMoura commented on MFE/container/src/i18n/translations/pt_br.success.i18n.json
> -    "createCertificate": "Certificado criado",
Here, I have removed this line because there is already a translation for 'createDevice' on line 22 of this file

2022-07-06 14:34 UTC, LeonamMoura commented on MFE/dashboard/src/i18n/translations/en.success.i18n.json
> -    "createCertificate": "Certificate created",
Here, I have removed this line because there is already a translation for 'createCertificate' on line 22 of this file

2022-07-08 13:33 UTC, LuanEdCosta approved these changes

2022-07-11 13:16 UTC, luisfelipefurlan approved these changes

2022-07-11 14:03 UTC, merged