[DOJOT-80] Feature: Making Dashboard Stepper Navigable
dojot/gui-v2 pull request #194
Opened 2022-07-19 17:51 UTC by LeonamMoura

https://dojot.atlassian.net/browse/DOJOT-80

2022-07-20 16:17 UTC, LuanEdCosta requested changes

2022-07-20 16:17 UTC, LuanEdCosta commented on MFE/dashboard/src/view/widget/wizard/wizard.jsx
>            {steps.map(({ label, key }) => (
What do you think of using the `index` of this map to navigate through steps. This way you don't need the `stepperNavigator` function.

2022-07-20 16:17 UTC, LuanEdCosta commented on MFE/dashboard/src/view/widget/wizard/wizard.jsx
> +      console.log(value);
Remove this console.log

2022-07-20 16:17 UTC, LuanEdCosta commented on MFE/dashboard/src/view/widget/wizard/wizard.jsx
> +      if (value.general.name.length < 5) {
What are these lines about? Why adding them in this PR?

2022-07-22 13:21 UTC, luisfelipefurlan requested changes

2022-07-22 13:21 UTC, luisfelipefurlan commented on MFE/dashboard/src/view/widget/wizard/wizard.jsx
> +  const stepperNavigator = label => {
You cannot define the steps inside the wizard component, each widget can have its own steps with an amount defined by the widget itself.

2022-07-22 13:21 UTC, luisfelipefurlan commented on MFE/dashboard/src/view/widget/wizard/wizard.jsx
> +        dispatchEvent(EVENT.GLOBAL_TOAST, {
Validation has to be done by the widget and not within the wizard. Each widget has to define its rules.

2022-07-26 14:42 UTC, LuanEdCosta approved these changes

2022-08-03 14:24 UTC, closed without merging