[DOJOT-141] [DOJOT-143] Feature - Device State
dojot/gui-v2 pull request #228
Opened 2022-11-08 19:57 UTC by LuanEdCosta

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
Cannot disable devices

* **What is the new behavior (if this is a feature change)?**
Now it is possible to disable devices.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
https://dojot.atlassian.net/browse/DOJOT-141
https://dojot.atlassian.net/browse/DOJOT-143

2022-11-09 14:13 UTC, LeonamMoura requested changes

2022-11-09 14:13 UTC, LeonamMoura commented on MFE/container/config/webpack.dev.js
> +    publicPath: 'http://localhost:8087/',
I think you forgot to back the port to 8080 here

2022-11-09 14:13 UTC, LeonamMoura commented on MFE/container/config/webpack.dev.js
> +    port: 8087,
I think you forgot to back the port to 8080 here

2022-11-09 15:05 UTC, LeonamMoura approved these changes
Good job 🚀

2022-11-09 16:46 UTC, luisfelipefurlan approved these changes

2022-11-18 19:26 UTC, ademirr approved these changes

2022-11-22 16:07 UTC, merged