[DOJOT-137] - Improved favorite device listing
dojot/gui-v2 pull request #270
Opened 2022-12-13 15:31 UTC by LeonamMoura

https://dojot.atlassian.net/browse/DOJOT-137

2022-12-14 16:33 UTC, LuanEdCosta reviewed
O que acha de remover aquele card "Importar/Exportar" neste PR mesmo? 
Ele está aí há muito tempo e ainda não funciona (nem tenho ideia de quando essa feature vai entrar).

2022-12-19 15:07 UTC, LuanEdCosta requested changes
**Todos os links da home estão quebrados.**

Para navegar para links fora do MFE atual precisa usar:

```javascript
dispatchEvent(EVENT.CHANGE_ROUTE, { pathname: '/PATH' });
```

2022-12-19 17:13 UTC, luisfelipefurlan requested changes

2022-12-19 17:13 UTC, luisfelipefurlan commented on MFE/home/src/view/View.jsx
> +                        onClick={() => history.push(`/devices/${device.id}`)}
Reverta a alteração para dispatchEvent(EVENT.CHANGE_ROUTE, { pathname: `/devices/${device.id}` })

2022-12-20 11:24 UTC, LuanEdCosta approved these changes

2022-12-20 11:30 UTC, merged