Map widget
dojot/gui-v2 pull request #36
Opened 2021-01-28 19:52 UTC by luisfelipefurlan

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
There's no map widget map at the current stage

* **What is the new behavior (if this is a feature change)?**
New map widget

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#1852

* **Other information**:

2021-01-29 16:28 UTC, mprevide requested changes
There are some notifications from CodeFactor and DeepScan

2021-02-01 20:43 UTC, cfrancisco submitted a review, later dismissed

2021-02-02 13:06 UTC, mprevide approved these changes

2021-02-04 17:50 UTC, cfrancisco approved these changes

2021-02-04 17:57 UTC, merged