Nx Feature - Certificates Management (List)
dojot/gui-v2 pull request #97
Opened 2021-11-05 15:43 UTC by LeonamMoura

2021-11-05 17:48 UTC, cfrancisco requested changes

2021-11-05 17:48 UTC, cfrancisco commented on src/js/views/Certificates/layout/AssociateDevicesModal.jsx
> +const fakeRows = [
Fake code rsrs..

2021-11-05 17:48 UTC, cfrancisco commented on src/js/views/Certificates/layout/AssociateDevicesModal.jsx
> +const fakeRows = [
It's a good practice always to review our code after sending it as PR.

2021-11-05 17:48 UTC, cfrancisco commented on src/js/views/Certificates/translations/en.certificates.i18n.json
> +    "associate": "Associar"
Missing i18n

2021-11-08 18:38 UTC, LuanEdCosta requested changes
Very good job! I found some small mistakes, but you're doing great, never stop learning :rocket:

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/View.jsx
> +          <SearchBar />
The SearchBar component receives some props to change the view mode and search certificates. You should pass these props.

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/layout/Cards.jsx
> +const Cards = ({
You should remove everything related to devices, such as favorite buttons, attrs, and use this component in the `certificates/View.jsx` component.

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/layout/EmptyDeviceList.jsx
> +const EmptyCertificateList = () => {
Use this component in the `certificates/View.jsx` component

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/layout/MassActions.jsx
> +const MassActions = ({
The only button that should be on this component is delete all. Users cannot add certificates to favorites and the create certificates button is meaningless here.

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/View.jsx
> +        <Pagination />
Missing props for the `<Pagination />` component

2021-11-08 18:38 UTC, LuanEdCosta commented on src/js/views/Certificates/layout/SearchBar.jsx
> +          placeholder={t('searchInputPh')}
Create this placeholder in the translation files

2021-11-17 16:40 UTC, LuanEdCosta requested changes
Everything is very good! :rocket: 
But I found two small mistakes :sweat_smile:

2021-11-17 16:40 UTC, LuanEdCosta commented on src/js/views/Certificates/View.jsx
> +    <ViewContainer headerTitle='Certificados'>
Missing translations

2021-11-17 16:40 UTC, LuanEdCosta commented on src/js/views/Certificates/View.jsx
> +          numberOfSelectedDevices={selectedCertificates.length}
I think you can remove this prop :thinking:

2021-11-18 13:15 UTC, LuanEdCosta approved these changes
:rocket: LGTM

2021-11-18 17:11 UTC, cfrancisco approved these changes

2021-11-19 12:04 UTC, merged