2299 - device creation step 2
dojot/gui-v2 pull request #99
Opened 2021-11-09 16:55 UTC by luisfelipefurlan

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
added security step on device creation

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2299

* **Other information**:

2021-11-10 12:39 UTC, LuanEdCosta requested changes
Very good job :+1: 
---

2021-11-10 12:39 UTC, LuanEdCosta commented on src/js/views/createDevice/steps/SecurityStep/SecurityTable.jsx
> +                  <TableCell className={classes.clickableCell}>Nome do Certificado</TableCell>
Maybe you can use the certificate attributes here, example: `cert.label`, `cert.created`, `cert.expiration`. You can also use moment to format dates.

2021-11-10 12:39 UTC, LuanEdCosta commented on src/js/common/components/DataTable/DataTableHead.jsx
> +          {disableCheckbox ? undefined : (
I think that you can use the prop `disableCheckbox` to hide the `<TableCell>` on line 29 too. You can use the `startExtraCells` prop to add an extra `<TableCell>` in this component: `src/js/views/createDevice/steps/SecurityStep/SecurityTable.jsx`.

2021-11-10 18:18 UTC, cfrancisco submitted a review, later dismissed

2021-11-24 18:16 UTC, LuanEdCosta approved these changes
:rocket:

2021-11-24 18:25 UTC, merged